#!/usr/bin/env sh
# This file is part of mongojs. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/KisanHub/mongojs/master/COPYRIGHT. No part of mongojs, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2015 The developers of mongojs. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/KisanHub/mongojs/master/COPYRIGHT.


set -e
set -u

nginx_increaseUlimitOnMacOSXToMatchConfiguration()
{
	ulimit -Sn 1024
}

nginx_setPrefixPath()
{
	local path="$(dirname "$0")"
	cd "$path" 1>/dev/null 2>/dev/null
		nginx_prefixPath="$(pwd)"
	cd - 1>/dev/null 2>/dev/null
}

nginx_execute()
{
	nginx -p "$nginx_prefixPath" -c "$nginx_prefixPath"/configuration/nginx.conf "$@"
}

nginx_execute_start()
{
	nginx_execute
}

nginx_execute_stop()
{
	nginx_execute -s stop
}

nginx_execute_reconfigure()
{
	nginx_execute -s reload
}

nginx_main()
{
	nginx_increaseUlimitOnMacOSXToMatchConfiguration
	nginx_setPrefixPath
	
	if [ "$#" -eq 0 ]; then
		nginx_execute_start
	else
		nginx_execute_${1}
	fi
}

nginx_main "$@"
