'use strict';var ClassModule=function(a){return a}(ClassModule||{});ClassModule.polyfills=function(a){return a}(ClassModule.polyfills||{});"use strict";
ClassModule.polyfills=function(a){String.fromCodePoint||function(){var a=function(){try{var a={},b=Object.defineProperty,d=b(a,a,a)&&b}catch(c){}return d}(),b=String.fromCharCode,d=Math.floor,c=function(a){var c=[],e,h,f=-1,k=arguments.length;if(!k)return"";for(var l="";++f<k;){h=Number(arguments[f]);if(!isFinite(h)||0>h||1114111<h||d(h)!=h)throw RangeError("Invalid code point: "+h);65535>=h?c.push(h):(h-=65536,e=(h>>10)+55296,h=h%1024+56320,c.push(e,h));if(f+1==k||16384<c.length)l+=b.apply(null,
c),c.length=0}return l};a?a(String,"fromCodePoint",{value:c,configurable:!0,writable:!0}):String.fromCodePoint=c}();return a}(ClassModule.polyfills||{});"use strict";ClassModule=function(a){a.functionName=function(a){return a.name?a.name:/^function\s+([\w\$]+)\s*\(/.exec(a.toString())[1]};return a}(ClassModule||{});"use strict";ClassModule=function(a){a.default=function(a,b){return"undefined"!==typeof a?a:b};return a}(ClassModule||{});"use strict";
ClassModule=function(a){a.isUndefined=function(){return"undefined"===typeof value};return a}(ClassModule||{});"use strict";ClassModule=function(a){a.template=function(a,b,d){for(var c="function"===typeof b,g=c?"__tpl"+ +new Date:"",m=JSON.stringify,n=/\$\{([\S\s]*?)\}/g,h=[],f=0,k;k=n.exec(a);)h.push(m(a.slice(f,n.lastIndex-k[0].length)),g+"("+k[1]+")"),f=n.lastIndex;h.push(m(a.slice(f)));return Function(g,"with(this)return"+h.join("+")).call(c?d:b,c&&b)};return a}(ClassModule||{});"use strict";
ClassModule=function(a){a.safeHasOwnProperty=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};return a}(ClassModule||{});"use strict";
ClassModule=function(a){a.Object=function(){};a.Object.prototype.constructor=function(){};a.Object.extend=function(e,b){function d(a,b){a.module=e;a.className=h;a.$=n;m[b]=a}function c(a){switch(a){case "constructor":throw"A definition can not be called 'constructor'";case "super":throw"A definition can not be called 'super'";case "supercall":throw"A definition can not be called 'super'";}}var g=function(){this.super=function(a){a.$.constructor.apply(this,Array.prototype.slice.call(arguments,1))};
this.supercall=function(b){var d=a.functionName(b);b.$[d].apply(this,Array.prototype.slice.call(arguments,1))};arguments[0]!==a.Object&&this.constructor.apply(this,arguments)},m=new this(a.Object),n=this.prototype,h=a.functionName(b);d(b,"constructor");Array.prototype.slice.call(arguments).forEach(function(b){if(b instanceof Function){var g=a.functionName(b);c(g);d(b,g)}else for(g in b){c(g);var h=b[g];h instanceof Function?d(h,g):m[g]=h}});g.prototype=m;g.extend=this.extend;return e[h]=g};return a}(ClassModule||
{});"use strict";ClassModule=function(a){a.Object.extend(a,function b(a){this.super(b);this.name=this.constructor.className;this.message=a},function(){return this.message});return a}(ClassModule||{});"use strict";ClassModule=function(a){a.Exception.extend(a,function b(d,c){this.super(b,a.template(d,a.default(c,{})))});return a}(ClassModule||{});"use strict";ClassModule=function(a){a.TemplatedException.extend(a,function b(d,c){this.super(b,d,a.default(c,{}))});return a}(ClassModule||{});"use strict";
ClassModule=function(a){a.Exception.extend(a,function b(a){this.super(b,a)});return a}(ClassModule||{});"use strict";var ClassModule=function(a){a.Exception.extend(a,function b(){this.super(b,"This is a virtual method that should have been overridden")});return a}(ClassModule||{}),MongoModule=function(a){return a}(MongoModule||{});"use strict";MongoModule=function(a){a.maximumBatchSize=512;a.maximumDocumentSize=16777216;a.maximumMessageSize=33554432;return a}(MongoModule||{});"use strict";
MongoModule=function(a){ClassModule.Object.extend(a,function b(a,c,g,m,n,h,f){this.super(b);this.isReplicaSetMember=a||c||g||m||n;this.isReplicaSetMemberPrimary=a;this.isReplicaSetMemberSecondary=c;this.isReplicaSetMemberArbiter=g;this.isReplicaSetMemberOther=m;this.isReplicaSetMemberGhost=n;this.isShardRouter=h;this.isStandalone=f;Object.freeze(this)},function(){return this.isStandalone},function(){return this.isReplicaSetMember},function(){return this.isShardRouter});a.ServerTypes=Object.freeze({REPLICA_SET_PRIMARY:new a.ServerType(!0,
!1,!1,!1,!1,!1,!1),REPLICA_SET_SECONDARY:new a.ServerType(!1,!0,!1,!1,!1,!1,!1),REPLICA_SET_ARBITER:new a.ServerType(!1,!1,!0,!1,!1,!1,!1),REPLICA_SET_OTHER:new a.ServerType(!1,!1,!1,!0,!1,!1,!1),REPLICA_SET_GHOST:new a.ServerType(!1,!1,!1,!1,!0,!1,!1),SHARD_ROUTER:new a.ServerType(!1,!1,!1,!1,!1,!0,!1),STANDALONE:new a.ServerType(!1,!1,!1,!1,!1,!1,!0)});return a}(MongoModule||{});MongoModule.BsonValues=function(a){return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){var e;e=new ArrayBuffer(2);(new DataView(e)).setInt16(0,256,!0);e=256===(new Int16Array(e))[0];a.isLittleEndian=e;return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.restrictBinaryToDataView=function(a){if(a instanceof DataView)return a;if(a instanceof ArrayBuffer)return new DataView(a,0,a.byteLength);var b=subbtype.buffer;if(b instanceof ArrayBuffer)return new DataView(b,a.byteOffset,a.byteLength);if(a instanceof Blob||a instanceof File)throw new ClassModule.IllegalArgumentException("value can not be a Blob or File");if(a instanceof String||"string"===typeof a)throw new ClassModule.IllegalArgumentException("Binary strings are not currently supported");
if(a instanceof Array||a instanceof Arguments)throw new ClassModule.IllegalArgumentException("Array and Arguments are not currently supported");};return a}(MongoModule.BsonValues||{});"use strict";MongoModule.BsonValues=function(a){a.toHexString=function(a,b){var d="",c,g;b?(c=a.byteLength-1,g=-1):(c=0,g=a.byteLength);for(;c!=g;){var m=a.getUint8(c),m=Number(m).toString(16),d=d+(1==m.length?"0"+m:m);c+=b?-1:1}return d};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){function e(a){return 26>a?a+65:52>a?a+71:62>a?a-4:62===a?43:63===a?47:65}a.base64Encode=function(a,d,c){for(var g=2,m="",n=0,h=0;h<c;h++)if(g=h%3,n|=a[h+d]<<(16>>>g&24),2===g||1===c-h)m+=String.fromCharCode(e(n>>>18&63),e(n>>>12&63),e(n>>>6&63),e(n&63)),n=0;return m.substr(0,m.length-2+g)+(2===g?"":1===g?"=":"==")};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.base64Decode=function(a){a=a.replace(/[^A-Za-z0-9\+\/]/g,"");for(var b=a.length,d=1*Math.ceil((3*b+1>>2)/1),c=new Uint8Array(d),g,m=0,n=0,h=0;h<b;h++)if(g=h&3,a.charCodeAt(h),m|=NaN<<18-6*g,3===g||1===b-h){for(g=0;3>g&&n<d;g++,n++)c[n]=m>>>(16>>>g&24)&255;m=0}return c.buffer};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){function e(a,h){var f=a[0],k=a[1],l=a[2],e=a[3],f=d(f,k,l,e,h[0],7,-680876936),e=d(e,f,k,l,h[1],12,-389564586),l=d(l,e,f,k,h[2],17,606105819),k=d(k,l,e,f,h[3],22,-1044525330),f=d(f,k,l,e,h[4],7,-176418897),e=d(e,f,k,l,h[5],12,1200080426),l=d(l,e,f,k,h[6],17,-1473231341),k=d(k,l,e,f,h[7],22,-45705983),f=d(f,k,l,e,h[8],7,1770035416),e=d(e,f,k,l,h[9],12,-1958414417),l=d(l,e,f,k,h[10],17,-42063),k=d(k,l,e,f,h[11],22,-1990404162),f=d(f,k,l,e,h[12],7,1804603682),e=d(e,
f,k,l,h[13],12,-40341101),l=d(l,e,f,k,h[14],17,-1502002290),k=d(k,l,e,f,h[15],22,1236535329),f=c(f,k,l,e,h[1],5,-165796510),e=c(e,f,k,l,h[6],9,-1069501632),l=c(l,e,f,k,h[11],14,643717713),k=c(k,l,e,f,h[0],20,-373897302),f=c(f,k,l,e,h[5],5,-701558691),e=c(e,f,k,l,h[10],9,38016083),l=c(l,e,f,k,h[15],14,-660478335),k=c(k,l,e,f,h[4],20,-405537848),f=c(f,k,l,e,h[9],5,568446438),e=c(e,f,k,l,h[14],9,-1019803690),l=c(l,e,f,k,h[3],14,-187363961),k=c(k,l,e,f,h[8],20,1163531501),f=c(f,k,l,e,h[13],5,-1444681467),
e=c(e,f,k,l,h[2],9,-51403784),l=c(l,e,f,k,h[7],14,1735328473),k=c(k,l,e,f,h[12],20,-1926607734),f=b(k^l^e,f,k,h[5],4,-378558),e=b(f^k^l,e,f,h[8],11,-2022574463),l=b(e^f^k,l,e,h[11],16,1839030562),k=b(l^e^f,k,l,h[14],23,-35309556),f=b(k^l^e,f,k,h[1],4,-1530992060),e=b(f^k^l,e,f,h[4],11,1272893353),l=b(e^f^k,l,e,h[7],16,-155497632),k=b(l^e^f,k,l,h[10],23,-1094730640),f=b(k^l^e,f,k,h[13],4,681279174),e=b(f^k^l,e,f,h[0],11,-358537222),l=b(e^f^k,l,e,h[3],16,-722521979),k=b(l^e^f,k,l,h[6],23,76029189),
f=b(k^l^e,f,k,h[9],4,-640364487),e=b(f^k^l,e,f,h[12],11,-421815835),l=b(e^f^k,l,e,h[15],16,530742520),k=b(l^e^f,k,l,h[2],23,-995338651),f=g(f,k,l,e,h[0],6,-198630844),e=g(e,f,k,l,h[7],10,1126891415),l=g(l,e,f,k,h[14],15,-1416354905),k=g(k,l,e,f,h[5],21,-57434055),f=g(f,k,l,e,h[12],6,1700485571),e=g(e,f,k,l,h[3],10,-1894986606),l=g(l,e,f,k,h[10],15,-1051523),k=g(k,l,e,f,h[1],21,-2054922799),f=g(f,k,l,e,h[8],6,1873313359),e=g(e,f,k,l,h[15],10,-30611744),l=g(l,e,f,k,h[6],15,-1560198380),k=g(k,l,e,f,
h[13],21,1309151649),f=g(f,k,l,e,h[4],6,-145523070),e=g(e,f,k,l,h[11],10,-1120210379),l=g(l,e,f,k,h[2],15,718787259),k=g(k,l,e,f,h[9],21,-343485551);a[0]=f+a[0]&4294967295;a[1]=k+a[1]&4294967295;a[2]=l+a[2]&4294967295;a[3]=e+a[3]&4294967295}function b(a,b,d,c,g,e){b=(b+a&4294967295)+(c+e&4294967295)&4294967295;return(b<<g|b>>>32-g)+d&4294967295}function d(a,d,c,g,e,m,p){return b(d&c|~d&g,a,d,e,m,p)}function c(a,d,c,g,e,m,p){return b(d&g|c&~g,a,d,e,m,p)}function g(a,d,c,g,e,m,p){return b(c^(d|~g),
a,d,e,m,p)}a.lowerCaseHexStringMd5FromDataView=function(b){return a.lowerCaseHexStringMd5FromUint8Array(new Uint8Array(b.buffer,b.byteOffset,b.byteLength))};a.lowerCaseHexStringMd5FromUint8Array=function(a){var b=a,d=b.length;a=[1732584193,-271733879,-1732584194,271733878];var c;for(c=64;c<=b.length;c+=64){for(var g=b.subarray(c-64,c),q=[],p=void 0,p=0;64>p;p+=4)q[p>>2]=g[p]+(g[p+1]<<8)+(g[p+2]<<16)+(g[p+3]<<24);e(a,q)}b=b.subarray(c-64);g=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(c=0;c<b.length;c++)g[c>>
2]|=b[c]<<(c%4<<3);g[c>>2]|=128<<(c%4<<3);if(55<c)for(e(a,g),c=0;16>c;c++)g[c]=0;g[14]=8*d;e(a,g);for(b=0;b<a.length;b++){d=a;c=b;g=a[b];q="";for(p=0;4>p;p++)q+=m[g>>8*p+4&15]+m[g>>8*p&15];d[c]=q}return a.join("")};var m="0123456789abcdef".split("");return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){var e=ClassModule.VirtualMethodException;ClassModule.Object.extend(a,function d(){this.super(d)},function(a){throw new e;},function(a,c){throw new e;},function(){throw new e;},function(){throw new e;},function(){throw new e;},function(){throw new e;});return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.BsonValue.extend(a,function b(a){this.super(b);this.code=a},function(a){return a.offset=this.writeBsonAt(a,a.offset)},function(){return this.code});return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractBsonValue.extend(a,function b(a,c,g){this.super(b,a);this.writeFunction=c;this.value=g},function(a,d){return a[this.writeFunction](this.value,d)},function(){return this.constructor.className+"("+this.value+")"});return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){function e(b,c,g){for(name in b)if(ClassModule.safeHasOwnProperty(b,name)){var e=b[name],e=e instanceof a.BsonValue?e[c]():e;g[name]=e}return g}function b(b){switch(b){case 1:return a.DoubleBsonValue;case 2:return a.StringBsonValue;case 3:return a.DocumentBsonValue;case 4:return a.ArrayBsonValue;case 5:return a.BinaryBsonValue;case 6:return a.UndefinedBsonValue;case 7:return a.ObjectIdBsonValue;case 8:return a.BooleanBsonValue;case 9:return a.UtcDateTimeBsonValue;
case 10:return a.NullBsonValue;case 11:return a.RegexBsonValue;case 12:return a.DbPointerBsonValue;case 13:return a.JavaScriptCodeBsonValue;case 14:return a.SymbolBsonValue;case 15:return a.JavaScriptCodeWithScopeBsonValue;case 16:return a.Int32BsonValue;case 17:return a.TimestampBsonValue;case 18:return a.Int64BsonValue;case 255:return a.MinKeyBsonValue;case 127:return a.MaxKeyBsonValue;default:throw new MongoModule.BsonReader.InvalidBsonException("Unknown element type code '${elementType}'",{elementType:b});
}}a.AbstractSingleBsonValue.extend(a,function c(a,b,e){this.super(c,a,b,e)},function(){return e(this.value,"toStrictJavaScriptValue",this.emptyDocument())},function(){return e(this.value,"toShellJavaScriptValue",this.emptyDocument())},function(){throw new ClassModule.VirtualMethodException;});a.AbstractObjectBsonValue.readBsonDocument=function(a,g,e){for(var n=a.readInt32()-4,n=a._guardUnderflow(a.offset,n)-1,h,f;a.offset<n;)h=a.readUint8(),f=b(h),h=a.readCString(),f=f.readBson(a),g[h]=f;if(a.offset!=
n)throw new MongoModule.BsonReader.InvalidBsonException("Invalid Document, terminalOffset was '${terminalOffset}' but reader.offset was '${offset}'",{terminalOffset:n,offset:a.offset});a.readTrailingNullByte();return new e(g)};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractBsonValue.extend(a,function b(a,c){this.super(b,a);this.emptyExpression=c},function(a,d){return d},function(){return this.constructor.className+"("+this.emptyExpression+")"});return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractSingleBsonValue.extend(a,function d(c,g){if(8!=a.restrictBinaryToDataView(g).byteLength)throw new ClassModule.IllegalArgumentException("value '${value}' must be 8 bytes long",{value:g});this.super(d,c,"writeInt64At",g)},function(){return this.constructor.className+"("+this.asString()+")"},function(){var a=this.toNumber();if(9007199254740991>=a&&-9007199254740991<=a&&Math.round(a)==a)return a.toString();if(goog.math.Long)return this.toGoogMathLong().toString();
if(dcodeIO.Long)return this.toDcodeIOLong(dcodeIO).toString();if(Long)return toMongoDbLong().toString();console.warn("Inaccurate BSON Int64 Long conversion toString");return a.toString()},function(){return new goog.math.Long(this.__highBitsSigned(),this.__lowBitsSigned)},function(a){return void 0===a?new Long(this.__highBitsSigned(),this.__lowBitsSigned,!1):new a.Long(this.__highBitsSigned(),this.__lowBitsSigned,!1)},function(a){return void 0===a?new Long(this.__highBitsSigned(),this.__lowBitsSigned):
new a.Long(this.__highBitsSigned(),this.__lowBitsSigned)},function(){return a.toHexString(this.value,!0)},function(){return this.__highBitsSigned()*e+this.__lowBitsUnsigned()},function(){return this.__lowBitsSigned()},function(){return 0==this.__highBitsSigned()&&0==this.__lowBitsSigned()},function(){return 0==this.__highBitsSigned()&&1==this.__lowBitsSigned()},function(){return 0!=this.__highBitsSigned()||0!=this.__lowBitsSigned()},function(){return 0>this.__highBitsSigned()},function(){return-2147483648==
this.__highBitsSigned()&&0==this.__lowBitsUnsigned()},function(){return this.value.getInt32(4,!0)},function(){return this.value.getInt32(0,!0)},function(){return this.value.getUint32(0,!0)});a.AbstractSigned64BitBsonValue.fromBits=function(a,c,g){var e=new DataView(new ArrayBuffer(8));e.setInt32(4,c,!0);e.setInt32(0,g,!0);return new a(e)};var e=4294967296;a.AbstractSigned64BitBsonValue.fromUnsigned32BitInteger=function(d,c){return a.AbstractSigned64BitBsonValue.fromBits(d,0,c)};return a}(MongoModule.BsonValues||
{});"use strict";MongoModule.BsonValues=function(a){a.AbstractSingleBsonValue.extend(a,function b(a){this.super(b,1,"writeDoubleAt",a)},function(){return this.value},function(){return this.toStrictJavaScriptValue()},function(){return 1==this.value}).readBson=function(b){return new a.DoubleBsonValue(b.readDouble())};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractSingleBsonValue.extend(a,function b(a){this.super(b,2,"writeStringAt",a)},function(){return this.value},function(){return this.toStrictJavaScriptValue()}).readBson=function(b){return new a.StringBsonValue(b.readString())};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractObjectBsonValue.extend(a,function b(a){this.super(b,3,"writeDocumentAt",a)},function(){return{}}).readBson=function(b){return a.AbstractObjectBsonValue.readBsonDocument(b,{},a.DocumentBsonValue)};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractObjectBsonValue.extend(a,function b(a){if(!(a instanceof Array))throw new ClassModule.IllegalArgumentException("value '${value}' must be an Array",{value:a});var c=0;for(name in a)if(ClassModule.safeHasOwnProperty(a,name)){if(name!==""+c)throw new ClassModule.IllegalArgumentException("value '${value}' must be an Array with contiguous numeric keys starting at zero (0)",{value:a});c+=1}this.super(b,4,"writeDocumentAt",a);this.length=a.length},function(){return[]},
function(){var a=Array.prototype.push.apply(this,Array.prototype.slice.apply(arguments));Object.defineProperty(this,name,{configurable:!0,enumerable:!0,get:function(){return this.value[a-1]},set:function(d){this.value[a-1]=d}});return a}).readBson=function(b){return a.AbstractObjectBsonValue.readBsonDocument(b,[],a.ArrayBsonValue)};a.ArrayBsonValue.push=Array.prototype.push;return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){var e=ClassModule.IllegalArgumentException;a.AbstractSingleBsonValue.extend(a,function d(c,g){if(c>a.BinaryBsonValue.LastDefinedBinarySubtype&&c<a.BinaryBsonValue.FirstUserDefinedBinarySubtype)throw new e("The binary subtype '${binarySubtype}' is reserved",{binarySubtype:c});var m=a.restrictBinaryToDataView(g);this.super(d,5);this.binarySubtype=c;this.value=m},function(a,c){return a.writeBinaryAt(this.binarySubType,this.value,c)},function(){var a=Number(this.binarySubtype).toString(16),
c={};c.$binary=this.__base64Encode();c.$type=a;return c},function(){return new BinData(this.binarySubtype,this.__base64Encode())},function(){var d=this.value;return a.base64Encode(d,d.byteOffset,d.byteLength)}).readBson=function(d){var c=d.readInt32(),g=d.readUint8();if(g>a.BinaryBsonValue.LastDefinedBinarySubtype&&g<a.BinaryBsonValue.FirstUserDefinedBinarySubtype)throw new MongoModule.BsonReader.InvalidBsonException("Unexpected binarySubtype value '${binarySubtype}'",{binarySubtype:g});d=d.readBytes(c);
return new a.BinaryBsonValue(g,d)};a.BinaryBsonValue.BinarySubtypes=Object.freeze({Generic:0,Function:1,BinaryOld:2,UuidOld:3,Uuid:4,Md5:5});a.BinaryBsonValue.LastDefinedBinarySubtype=a.BinaryBsonValue.BinarySubtypes.Md5;a.BinaryBsonValue.FirstUserDefinedBinarySubtype=128;return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractEmptyBsonValue.extend(a,function b(){this.super(b,6,"undefined");this.value=void 0},function(){return{$undefined:!0}},function(){}).readBson=function(b){return a.UndefinedBsonValue.Singleton};a.UndefinedBsonValue.Singleton=new a.UndefinedBsonValue;return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractSingleBsonValue.extend(a,function m(b){var d=a.restrictBinaryToDataView(b);if(12!=d.byteLength)throw new ClassModule.IllegalArgumentException("value '${value}' must be 12 bytes long",{value:b});this.super(m,7,"writeBytesAt",d)},function(){var a={};a.$oid=this.toHexString();return a},function(){return ObjectId(this.toHexString())},function(){return a.toHexString(this.value,!1)}).readBson=function(b){return new a.ObjectIdBsonValue(b.readBytes(12))};var e;
window.crypto&&window.crypto.getRandomValues?e=function(a){a=new Uint8Array(a);window.crypto.getRandomValues(a);return a}:(console.warn("You should upgrade your browser to one that supports window.crypto.getRandomValues"),e=function(a){for(var b=new Uint8Array(a),d,c=0;c<a;c++)d=255*Math.random()+0,b[c]=d;return b});var b=e(3),d=e(2),c=(new DataView(e(4).buffer)).getUint32(0);a.ObjectIdBsonValue.generateNewObjectId=function(){var e=c;c=4294967295==c?0:c+1;var n=Math.round(Date.now()/1E3),h=new DataView(new ArrayBuffer(12));
h.setInt32(0,n,!1);h.setUint8(4,b[0]);h.setUint8(5,b[1]);h.setUint8(6,b[2]);h.setUint8(7,d[0]);h.setUint8(8,d[1]);h.setUint8(9,e>>16&255);h.setUint8(10,e>>8&255);h.setUint8(11,e&255);return new a.ObjectIdBsonValue(h)};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractSingleBsonValue.extend(a,function b(a){if(!(a instanceof Boolean)&&"boolean"!==typeof a)throw new ClassModule.IllegalArgumentException("value '${value}' must be Boolean or boolean",{value:a});this.super(b,8);this.value=a},function(a,d){return a.writeByteAt(this.value?1:0,d)},function(){return this.value?!0:!1},function(){return this.toStrictJavaScriptValue()},function(){return this.value?!0:!1},function(){return!this.isTrue()}).readBson=function(b){b=b.readUint8();
switch(b){case 0:return a.BooleanBsonValue.BsonFalse;case 1:return a.BooleanBsonValue.BsonTrue;default:throw new MongoModule.BsonReader.InvalidBsonException("Unexpected boolean value '${raw}'",{raw:b});}};a.BooleanBsonValue.BsonFalse=new a.BooleanBsonValue(!0);a.BooleanBsonValue.BsonTrue=new a.BooleanBsonValue(!1);a.BooleanBsonValue.bsonBoolean=function(b){return b?a.BooleanBsonValue.BsonTrue:a.BooleanBsonValue.BsonFalse};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractSigned64BitBsonValue.extend(a,function b(a){this.super(b,9,a)},function(){var a={};a.$date=this.asString();return a},function(){var a=this.toNumber(),d=Date(a);return-590143968E5<=a&&253399536E6>=a?ISODate(d.toISOString()):d}).readBson=function(b){return new a.UtcDateTimeBsonValue(b.readInt64())};a.UtcDateTimeBsonValue.fromBits=function(b,d){return a.AbstractSigned64BitBsonValue.fromBits(a.UtcDateTimeBsonValue,b,d)};a.UtcDateTimeBsonValue.fromUnsigned32BitInteger=
function(b){return a.AbstractSigned64BitBsonValue.fromUnsigned32BitInteger(a.UtcDateTimeBsonValue,b)};return a}(MongoModule.BsonValues||{});"use strict";MongoModule.BsonValues=function(a){a.AbstractEmptyBsonValue.extend(a,function b(){this.super(b,10,"null");this.value=null},function(){return null},function(){return null}).readBson=function(b){return a.NullBsonValue.Singleton};a.NullBsonValue.Singleton=new a.NullBsonValue;return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractBsonValue.extend(a,function b(a,c){this.super(b,11);this.pattern=a;this.options=c;this.value=[a,c]},function(a,d){var c=a.writeCStringAt(this.pattern,c);return a.writeCStringAt(this.options,c)},function(){return this.constructor.className+"("+this.regex+", "+this.options+")"},function(){var a={};a.$regex=this.pattern;a.$options=this.options;return a},function(){return this.toRegExp()},function(){return new RegExp(this.pattern,this.options)}).readBson=function(b){return new a.RegexBsonValue(b.readCString(),
b.readCString())};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractBsonValue.extend(a,function b(a,c){if(!(c instanceof ObjectIdBsonValue))throw new ClassModule.IllegalArgumentException("objectId '${objectId}' must be instanceof ObjectIdBsonValue",{objectId:c});this.super(b,12);this.namespace=a;this.objectId=c;this.value=[a,c]},function(a,d){var c=a.writeStringAt(this.namespace,c);return a.writeBytesAt(this.objectId.dataView,c)},function(){return this.constructor.className+"("+this.string+", "+this.bytes+")"},function(){return this.__toJavaScript("toStrictJavaScriptValue")},
function(){return this.__toJavaScript("toShellJavaScriptValue")},function(a){var d={};d.$ref=this.namespace;d.$id=this.objectId[a]();return d}).readBson=function(b){return new a.DbPointerBsonValue(b.readString(),a.ObjectIdBsonValue.readBytes(12))};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractSingleBsonValue.extend(a,function b(a){this.super(b,13,"writeStringAt",a)},function(){var a={};a.$code=this.value;return a},function(){return this.toStrictJavaScriptValue()}).readBson=function(b){return new a.JavaScriptCodeBsonValue(b.readString())};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractSingleBsonValue.extend(a,function b(a){this.super(b,14,"writeStringAt",a)},function(){var a={};a.$symbol=this.value;return a},function(){return this.toStrictJavaScriptValue()}).readBson=function(b){return new a.SymbolBsonValue(b.readString())};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractBsonValue.extend(a,function b(d,c){var g;g=c instanceof DocumentBsonValue?c:new a.DocumentBsonValue(c);this.super(b,15);this.javaScriptCode=d;this.scopeDocument=g;this.value=[d,c]},function(a,d){var c;c=a.writeStringAt(this.javaScriptCode,d+4);c=a.writeDocumentAt(this.scopeDocument,c);a.writeInt32At(c-d,d);return c},function(){return this.constructor.className+"("+this.javaScriptCode+", "+this.scopeDocument+")"},function(){return this.__toJavaScript("toStrictJavaScriptValue")},
function(){return this.__toJavaScript("toShellJavaScriptValue")},function(a){var d={};d.$code=this.javaScriptCode;d.$scope=this.scopeDocument[a]();return d}).readBson=function(b){b.readInt32();var d=b.readString();b=a.DocumentBsonValue.readBson(b);return new a.JavaScriptCodeWithScopeBsonValue(d,b)};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractSingleBsonValue.extend(a,function b(a){this.super(b,16,"writeInt32At",a)},function(){return this.value},function(){return this.toStrictJavaScriptValue()},function(){return 0==this.value},function(){return 1==this.value},function(){return 0!=this.value},function(a){return this.value>a},function(){return this.value}).readBson=function(b){return new a.Int32BsonValue(b.readInt32())};a.Int32BsonValue.Zero=new a.Int32BsonValue(0);a.Int32BsonValue.One=new a.Int32BsonValue(1);
return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractBsonValue.extend(a,function b(a,c){this.super(b,17);this.unix32BitTime=a;this.ordinal=c;this.value=[a,c]},function(a,d){var c=a.writeInt32At(value.ordinal,d);return a.writeInt32At(value.unix32BitTime,c)},function(){return this.constructor.className+"("+this.unix32BitTime+", "+this.ordinal+")"},function(){var a={};a.$t=this.unix32BitTime;a.$i=this.ordinal;var d={};d.$timestamp=a;return d},function(){return Timestamp(this.unix32BitTime,this.ordinal)}).readBson=
function(b){var d=b.readInt32();b=b.readInt32();return new a.TimestampBsonValue(b,d)};return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractSigned64BitBsonValue.extend(a,function b(a){this.super(b,18,a)},function(){var a={};a.$numberLong=this.asString();return a},function(){var a=this.toNumber();return-2147483648<=a&&2147483647>=a?NumberLong(a):NumberLong(this.asString())}).readBson=function(b){return new a.Int64BsonValue(b.readInt64())};a.Int64BsonValue.fromBits=function(b,d){return a.AbstractSigned64BitBsonValue.fromBits(a.Int64BsonValue,b,d)};a.Int64BsonValue.fromUnsigned32BitInteger=function(b){return a.AbstractSigned64BitBsonValue.fromUnsigned32BitInteger(a.Int64BsonValue,
b)};return a}(MongoModule.BsonValues||{});"use strict";MongoModule.BsonValues=function(a){a.AbstractEmptyBsonValue.extend(a,function b(){this.super(b,255,"")},function(){return{$minKey:1}},function(){return this.toStrictJavaScriptValue()}).readBson=function(b){return a.MinKeyBsonValue.Singleton};a.MinKeyBsonValue.Singleton=new a.MinKeyBsonValue;return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){a.AbstractEmptyBsonValue.extend(a,function b(){this.super(b,127,"")},function(){return{$maxKey:1}},function(){return this.toStrictJavaScriptValue()}).readBson=function(b){return a.MaxKeyBsonValue.Singleton};a.MaxKeyBsonValue.Singleton=new a.MaxKeyBsonValue;return a}(MongoModule.BsonValues||{});"use strict";
MongoModule.BsonValues=function(a){function e(a){return(a|0)===a?new p(a):new t(a)}function b(a){a=a.$oid;for(var b=new DataView(new ArrayBuffer(12)),d=0;12>d;d++){var c=parseInt("0x"+a[2*d]+a[2*d+1]);b.setUint8(d,c)}return new f(b)}function d(a){var b="";a.ignoreCase&&(b+="i");a.lastIndex&&(b+="l");a.multiline&&(b+="m");return new v(a.source,b)}var c=a.BsonValue,g=a.DocumentBsonValue,m=a.ArrayBsonValue,n=a.TimestampBsonValue,h=a.SymbolBsonValue,f=a.ObjectIdBsonValue,k=a.base64Decode;a.fromStrictJavascript=
function(f){if(f instanceof c){if(f instanceof g){f=f.value;var u={};for(name in f)ClassModule.safeHasOwnProperty(f,name)&&(u[name]=a.fromStrictJavascript(f[name]));return new g(u)}return f instanceof m?f.value.map(function(b){return a.fromStrictJavascript(b)}):f}if(void 0===f)return a.UndefinedBsonValue.Singleton;if(null===f)return a.NullBsonValue.Singleton;u=typeof f;if("string"===u)return new l(f);if("boolean"===u)return q(f);if("number"===u)return e(f);if("object"===u){if(f instanceof String)return new l(f.valueOf());
if(f instanceof Boolean)return q(f.valueOf());if(f instanceof Number)return e(f.valueOf());if(f instanceof RegExp)return d(f);if(f instanceof Date)return new r(1E3*f.valueOf());if(f instanceof Array)return new m(f.map(function(b){return a.fromStrictJavascript(b)}));if(f instanceof ArrayBuffer||f instanceof DataView||f instanceof Uint8Array||f instanceof Uint16Array||f instanceof Uint32Array||f instanceof Int8Array||f instanceof Int16Array||f instanceof Int32Array||f instanceof Float32Array||f instanceof
Float64Array)return new x(w,f);if(f instanceof Function)return f;if(f.$date)return new r(parseInt(f.$date));if(f.$timestamp)return f=f.$timestamp,new n(f.$t,f.$i);if(f.$symbol)return new h(f.$symbol);if(f.$oid)return b(f);if(f.$minKey)return a.MinKeyBsonValue.Singleton;if(f.$maxKey)return a.MaxKeyBsonValue.Singleton;if(f.$code)return f.$scope?new a.JavaScriptCodeWithScopeBsonValue(f.$code,f.$scope):new a.JavaScriptCode(f.$code);if(f.$numberLong){f=f.$numberLong;if(goog.math.Long.fromString)return f=
goog.math.Long.fromString(f,10),a.Int64BsonValue.fromBits(f.high_,f.low_);if(dcodeIO.Long)return f=dcodeIO.Long.fromString(f,!1,10),a.Int64BsonValue.fromBits(f.high,f.low);if(Long)return f=Long.fromString(f,10),a.Int64BsonValue.fromBits(f.getHighBits(),f.getLowBits());console.warn("Potential loss of precision in converting from string to Int64BsonValue");return a.Int64BsonValue.fromUnsigned32BitInteger(parseInt(f,10))}if(f.$ref)return new a.DbPointerBsonValue(f.$ref,b(f.$id));if(f.$binary)return new x(parseInt("0x"+
f.$type),k(f.$binary));u={};for(name in f)ClassModule.safeHasOwnProperty(f,name)&&(u[name]=a.fromStrictJavascript(f[name]));return new g(u)}throw"Don't know what to do!";};var l=a.StringBsonValue,q=a.BooleanBsonValue.bsonBoolean,p=a.Int32BsonValue,t=a.DoubleBsonValue,v=a.RegexBsonValue,r=a.UtcDateTimeBsonValue,x=a.BinaryBsonValue,w=a.BinaryBsonValue.BinarySubtypes.Generic;return a}(MongoModule.BsonValues||{});MongoModule.Messages=function(a){return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){a.isBitSet=function(a,b){return 0!=(1<<b&a)};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){a.guardZeroInt32=function(a){if(0!=a)throw new ClassModule.IllegalArgumentException("zeroInt32 '${zeroInt32}' is not zero (0)",{zeroInt32:a});};a.guardFlagsDoesNotExceed=function(a,b,d){d=ClassModule.default(d,"flagsInt32");if(a>b)throw new ClassModule.IllegalArgumentException("${ourName} '${flagsInt32}' can can not be greater than ${canNotBeGreaterThan}",{ourName:d,flagsInt32:a,canNotBeGreaterThan:b});};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){ClassModule.TemplatedException.extend(a,function b(a,c){this.super(b,a,c)});return a}(MongoModule.Messages||{});"use strict";MongoModule.Messages=function(a){ClassModule.Object.extend(a,function b(){this.super(b)},function(a){throw new ClassModule.VirtualMethodException;}).readMessage=function(b){return a.AbstractMessage.readMessage(b)};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){function e(d){switch(d){case a.OpCodes.OP_REPLY:return a.ReplyMessage;case a.OpCodes.OP_MSG:return a.MsgMessage;case a.OpCodes.OP_UPDATE:return a.UpdateMessage;case a.OpCodes.OP_INSERT:return a.InsertMessage;case 2003:throw new b("opCode '${opCode}' is 'RESERVED', formerly OP_GET_BY_OID",{opCode:d});case a.OpCodes.OP_QUERY:return a.QueryMessage;case a.OpCodes.OP_GET_MORE:return a.GetMoreMessage;case a.OpCodes.OP_DELETE:return a.DeleteMessage;case a.OpCodes.OP_KILL_CURSORS:return a.KillCursorsMessage;
default:throw new b("Unknown opCode '${opCode}'",{opCode:d});}}var b=a.InvalidMessageException;a.Message.extend(a,function c(a,b,e){this.super(c);this.requestIdInt32=a;this.responseToInt32=b;this.opCodeInt32=e},function(a){var b=a.offset;a.skipInt32();a.writeInt32(this.requestIdInt32);a.writeInt32(this.responseToInt32);a.writeInt32(this.opCodeInt32);this.writeBsonContents(a);var e=a.offset-b;a.writeInt32At(e,b);return e},function(a){throw new ClassModule.VirtualMethodException;}).readMessage=function(a){var b=
a.readInt32(),b=a._guardUnderflow(a.offset,b-4),m=a.readInt32(),n=a.readInt32(),h=a.readInt32();return e(h).readMessageContents(a,b,m,n)};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){(a.OpCodes=a.OpCodes||{}).OP_MSG=1E3;a.AbstractMessage.extend(a,function b(d,c,g){this.super(b,d,c,a.OpCodes.OP_MSG);this.message=g},function(a){a.writeCstring(this.message)}).readMessageContents=function(b,d,c,g){throw new a.InvalidMessageException("Did not expect a MsgMessage in reply",{});};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){(a.OpCodes=a.OpCodes||{}).OP_UPDATE=2001;a.AbstractMessage.extend(a,function b(d,c,g,m,n,h,f){a.guardZeroInt32(g);a.guardFlagsDoesNotExceed(n,3);this.super(b,d,c,a.OpCodes.OP_UPDATE);this.zeroInt32=g;this.fullCollectionName=m;this.flagsInt32=n;this.selectorDocument=h;this.updateDocument=f},function(a){a.writeInt32(this.zeroInt32);a.writeCstring(this.fullCollectionName);a.writeInt32(this.flagsInt32);a.write(this.selectorDocument);a.write(this.updateDocument)}).readMessageContents=
function(b,d,c,g){throw new a.InvalidMessageException("Did not expect an UpdateMessage in reply",{});};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){(a.OpCodes=a.OpCodes||{}).OP_INSERT=2002;a.AbstractMessage.extend(a,function b(d,c,g,m,n){a.guardFlagsDoesNotExceed(g,1);this.super(b,d,c,a.OpCodes.OP_INSERT);this.flagsInt32=g;this.fullCollectionName=m;this.documents=n},function(a){a.writeInt32(this.flagsInt32);a.writeCstring(this.fullCollectionName);this.documents.forEach(function(d){d.writeBson(a)})}).readMessageContents=function(b,d,c,g){throw new a.InvalidMessageException("Did not expect an InsertMessage in reply",
{});};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){(a.OpCodes=a.OpCodes||{}).OP_QUERY=2004;a.AbstractMessage.extend(a,function b(d,c,g,m,n,h,f,k){a.guardFlagsDoesNotExceed(g,255);if(a.isBitSet(g,0))throw new ClassModule.IllegalArgumentException("flagsInt32 '${flagsInt32}' must not have bit 0 set",{flagsInt32:g});this.super(b,d,c,a.OpCodes.OP_QUERY);this.flagsInt32=g;this.fullCollectionName=m;this.numberToSkipInt32=n;this.numberToReturnInt32=h;this.queryDocument=f;this.returnFieldsSelectorDocument=ClassModule.default(k,
null)},function(a){a.writeInt32(this.flagsInt32);a.writeCstring(this.fullCollectionName);a.writeInt32(this.numberToSkipInt32);a.writeInt32(this.numberToReturnInt32);a.write(this.queryDocument);null!==this.returnFieldsSelectorDocument&&a.write(this.returnFieldsSelectorDocument)}).readMessageContents=function(b,d,c,g){throw new a.InvalidMessageException("Did not expect a QueryMessage in reply",{});};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){(a.OpCodes=a.OpCodes||{}).OP_GET_MORE=2005;a.AbstractMessage.extend(a,function b(d,c,g,m,n,h){a.guardZeroInt32(g);this.super(b,d,c,a.OpCodes.OP_GET_MORE);this.zeroInt32=g;this.fullCollectionName=m;this.numberToReturnInt32=n;this.cursorIdInt64=h},function(a){a.writeInt32(this.zeroInt32);a.writeCstring(this.fullCollectionName);a.writeInt32(this.numberToReturnInt32);a.write(this.cursorIdInt64)}).readMessageContents=function(b,d,c,g){throw new a.InvalidMessageException("Did not expect a GetMoreMessage in reply",
{});};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){(a.OpCodes=a.OpCodes||{}).OP_DELETE=2006;a.AbstractMessage.extend(a,function b(d,c,g,m,n,h){a.guardZeroInt32(g);a.guardFlagsDoesNotExceed(n,1);this.super(b,d,c,a.OpCodes.OP_DELETE);this.zeroInt32=g;this.fullCollectionName=m;this.flagsInt32=n;this.selectorDocument=h},function(a){a.writeInt32(this.zeroInt32);a.writeCstring(this.fullCollectionName);a.writeInt32(this.flagsInt32);this.selectorDocument.writeBson(a)}).readMessageContents=function(b,d,c,g){throw new a.InvalidMessageException("Did not expect a DeleteMessage in reply",
{});};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){(a.OpCodes=a.OpCodes||{}).OP_KILL_CURSORS=2007;a.AbstractMessage.extend(a,function b(d,c,g,m){a.guardZeroInt32(g);a.guardFlagsDoesNotExceed(flagsInt32,1);this.super(b,d,c,a.OpCodes.OP_KILL_CURSORS);this.zeroInt32=g;this.cursorIdInt64s=m},function(a){a.writeInt32(this.zeroInt32);a.writeInt32(this.cursorIdInt64s.length);this.cursorIdInt64s.forEach(function(d){a.write(d)})}).readMessageContents=function(b,d,c,g){throw new a.InvalidMessageException("Did not expect a KillCursorsMessage in reply",{});
};return a}(MongoModule.Messages||{});"use strict";
MongoModule.Messages=function(a){(a.OpCodes=a.OpCodes||{}).OP_REPLY=1;var e=ClassModule.TemplatedException,b=MongoModule.Messages.GetMoreMessage,d=MongoModule.Messages.KillCursorsMessage,c=MongoModule.BsonValues.DocumentBsonValue,g=MongoModule.BsonValues.Int64BsonValue;a.AbstractMessage.extend(a,function n(b,d,c,e,g,p){a.guardFlagsDoesNotExceed(c,15,"responseFlagsInt32");this.super(n,b,d,a.OpCodes.OP_REPLY);this.responseFlagsInt32=c;this.cursorIdInt64=e;this.startingFromInt32=g;this.documents=p},
function(a){a.writeInt32(this.responseFlagsInt32);a.write(this.cursorIdInt64);a.writeInt32(this.startingFromInt32);a.writeInt32(this.documents.length);this.documents.forEach(function(b){a.write(b)})},function(a,c){var f=c[this.responseToInt32];if(!f)throw"No known resultHandlerTuple for responseToInt32 "+this.responseToInt32;delete c[this.responseToInt32];var g=f.resultHandler,l=this.cursorIdInt64.isNotZero(),q=this.wasCursorNotFound(),p=this.didGetMoreOrQueryButNotCommandFail(),t=g.results(this.documents,
l,q,p);if(q||p){if(t.getMore)throw new e("getMoreTuple.getMore was true but moreAvailable was false",{});}else if(l)l=f.fullCollectionName,q=c.nextRequestId(),t.getMore?a.send(l,g,new b(q,this.requestIdInt32,0,f.fullCollectionName,t.batchSize,this.cursorIdInt64)):a.send(l,null,new d(q,this.requestIdInt32,0,[this.cursorIdInt64]));else if(t.getMore)throw new e("getMoreTuple.getMore was true but moreAvailable was false",{});},function(){return this.isResponseFlagBitSet(0)},function(){return this.isResponseFlagBitSet(1)},
function(){return this.isResponseFlagBitSet(2)},function(){return this.isResponseFlagBitSet(3)},function(b){return a.isBitSet(this.responseFlagsInt32,b)}).readMessageContents=function(b,d,e,k){for(var l=b.readInt32(),q=new g(b.readInt64()),p=b.readInt32(),t=b.readInt32(),v=[],r=0;r<t;r++)v.push(c.readBson(b));if(b.offset!=d)throw new a.InvalidMessageException("Expected an offset of '${terminalOffset}' but got an offset of '${offset}'",{terminalOffset:d,offset:b.offset});return new a.ReplyMessage(e,
k,l,q,p,v)};return a}(MongoModule.Messages||{});MongoModule.BsonWriter=function(a){return a}(MongoModule.BsonWriter||{});"use strict";MongoModule.BsonWriter=function(a){ClassModule.TemplatedException.extend(a,function b(a,c,g){this.super(b,"The offset ${offset} + required space ${requiredSpace} exceeds the maximum length ${maximumLength}, causing overflow",{offset:a,requiredSpace:c,maximumLength:g})});return a}(MongoModule.BsonWriter||{});"use strict";
MongoModule.BsonWriter=function(a){ClassModule.IllegalArgumentException.extend(a,function b(a,c,g){this.super(b,"The string '${string}' at index '${index}' ${description}",{string:a,index:c,description:g})});return a}(MongoModule.BsonWriter||{});"use strict";
MongoModule.BsonWriter=function(a){ClassModule.IllegalArgumentException.extend(a,function b(a,c){this.super(b,"The unicode code point '${invalidUnicodeCodePoint}' ${description}",{invalidUnicodeCodePoint:a,description:c})});return a}(MongoModule.BsonWriter||{});"use strict";
MongoModule.BsonWriter=function(a){function e(b,d,c){var e=b+d;if(e>c)throw new a.BsonWriterOverflowException(b,d,c);return e}ClassModule.Object.extend(a,function(a){this.dataView=new DataView(a);this.maximumLength=this.dataView.byteLength;this.offset=0},function(a){return this.offset=this.writeAt(a,this.offset)},function(a,d){return a.writeBsonAt(this,d)},function(a,d){var c=this.writeElementListAt(a,d+4),c=this.writeByteAt(0,c);this.writeInt32At(c-d,d);return c},function(a){return this.offset=this.writeDocumentAt(a,
this.offset)},function(a,d){var c=d;for(name in a)if(ClassModule.safeHasOwnProperty(a,name)){var e=a[name];e instanceof MongoModule.BsonValues.BsonValue?c=this.writeElementAt(name,e,c):e instanceof Function||console.warn("Non-BSON value '"+e+"' for name '"+name+"' not serialized")}return c},function(a){return this.offset=this.writeElementListAt(a,this.offset)},function(a,d,c){c=this.writeByteAt(d.elementType(),c);c=this.writeCstringAt(a,c);return c=d.writeBsonAt(this,c)},function(a,d){return e(a,
d,this.maximumLength)},function(a){return this.offset+=a},function(){return this.skip(1)},function(a){return this.offset=this.writeByteAt(a,this.offset)},function(a,d){var c=this._guardOverflow(d,1);this.dataView.setUint8(d,a);return c},function(){return this.skip(4)},function(a){return this.offset=this.writeInt32At(a,this.offset)},function(a,d){var c=this._guardOverflow(d,4);this.dataView.setInt32(d,a,!0);return c},function(){return this.skip(8)},function(a){return this.offset=this.writeInt64At(a,
this.offset)},function(a,d){var c=this._guardOverflow(d,8);this.dataView.setFloat64(d,a.getFloat64(0,!0),!0);return c},function(){return this.skip(8)},function(a){return this.offset=this.writeDoubleAt(a,this.offset)},function(a,d){var c=this._guardOverflow(d,8);this.dataView.setFloat64(d,a,!0);return c},function(a,d){var c=d+4,e=this._writeStringWithTrailingNullAt(a,!1,c);this.writeInt32At(e-c,d);return e},function(a){return this.offset=this.writeStringAt(a,this.offset)},function(a,d){return this._writeStringWithTrailingNullAt(a,
!0,d)},function(a){return this.offset=this.writeCstringAt(a,this.offset)},function(a,d,c){this._guardOverflow(c,5+a.byteLength);this.dataView.writeByte(c+4,d);a=this.writeBytesAt(a,c+4+1);this.writeInt32At(a-c-4-1,c);return a},function(a,d){return this.offset=this.writeBinaryAt(a,d,this.offset)},function(a,d){var c=this.dataView,c=new Uint8Array(c.buffer,c.byteOffset,c.byteLength),e=new Uint8Array(a.buffer,a.byteOffset,a.byteLength);c.set(e,d);return d+a.byteLength},function(a){return this.offset=
this.writeBytesAt(a,offset)},function(b,d,c){b=a.writeUtf16BigEndianStringAsUtf8At(this.dataView,b,d,c,this.maximumLength);return this.writeByteAt(0,b)});a.writeUnicodeCodePointAsUtf8At=function(b,d,c,g){if(128>d)g=e(c,1,g),b.setUint8(c,d,c);else if(2047>=d)g=tguardOverflow(c,2,g),b.setUint8(c,(code_point>>6)+192),b.setUint8(c+1,(code_point&63)+128);else if(65535>=d)g=e(c,3,g),b.setUint8(c,(code_point>>12)+224),b.setUint8(c+1,(code_point>>6&63)+128),b.setUint8(c+2,(code_point&63)+128);else if(1114111>=
d)g=e(c,4,g),b.setUint8(c,(code_point>>18)+240),b.setUint8(c+1,(code_point>>12&63)+128),b.setUint8(c+2,(code_point>>6&63)+128),b.setUint8(c+3,(code_point&63)+128);else throw new a.InvalidUnicodeCodePointException(d,"is greater than 0x10FFFFF");return g};a.writeUtf16BigEndianStringAsUtf8At=function(b,d,c,e,m){for(var n=d.length,h=0;h<n;){var f=d.charCodeAt(h);if(55296>f||57343<f){if(0==f&&c)throw new a.InvalidUtf16StringException(d,h,"has code point zero (NUL); this is not allowed in the current context");
e=a.writeUnicodeCodePointAsUtf8At(b,f,e,m);h++}else if(55296<=f&&56319>=f){if(h=n-1)throw new a.InvalidUtf16StringException(d,h,"has a leading high surrogate but no subsequent low surrogate (there are not more UTF-16 characters)");var k=d.charCodeAt(h+1);if(56320>k||56319>k)throw new a.InvalidUtf16StringException(d,h,"has a leading high surrogate but no subsequent low surrogate");e=a.writeUnicodeCodePointAsUtf8At(b,(f<<10)+k-56613888,e,m);h+=2}}return e};return a}(MongoModule.BsonWriter||{});
MongoModule.BsonReader=function(a){return a}(MongoModule.BsonReader||{});"use strict";MongoModule.BsonReader=function(a){ClassModule.TemplatedException.extend(a,function b(a,c,g){this.super(b,"The offset ${offset} + required space ${requiredSpace} exceeds the maximum length ${maximumLength}, causing underflow",{offset:a,requiredSpace:c,length:g})});return a}(MongoModule.BsonReader||{});"use strict";
MongoModule.BsonReader=function(a){ClassModule.TemplatedException.extend(a,function b(a,c){this.super(b,a,c)});return a}(MongoModule.BsonReader||{});"use strict";MongoModule.BsonReader=function(a){ClassModule.TemplatedException.extend(a,function b(a,c){this.super(b,a,c)});return a}(MongoModule.BsonReader||{});"use strict";
MongoModule.BsonReader=function(a){var e=a.InvalidBsonException;ClassModule.Object.extend(a,function(a){this.dataView=new DataView(a);this.maximumLength=this.dataView.byteLength;this.offset=0},function(){if(this.offset+4>this.maximumLength)return!1;var a=this.dataView.getInt32(this.offset,!0);return this.offset+a>this.maximumLength?!1:!0},function(b,d){var c=b+d,e=this.maximumLength;if(c>e)throw new a.BsonReaderUnderflowException(b,d,e);return c},function(){this.offset-=4},function(){var a=this._guardUnderflow(this.offset,
4);try{return this.dataView.getInt32(this.offset,!0)}finally{this.offset=a}},function(){return this.readBytes(8)},function(){var a=this._guardUnderflow(this.offset,8);try{return this.dataView.getFloat64(this.offset,!0)}finally{this.offset=a}},function(){var a=this._guardUnderflow(this.offset,1);try{return this.dataView.getUint8(this.offset)}finally{this.offset=a}},function(a){var d=this._guardUnderflow(this.offset,a);try{var c=this.dataView.byteOffset+this.offset;return new DataView(this.dataView.buffer.slice(c,
c+a))}finally{this.offset=d}},function(){var a="",d;do{d=this.readUtf8EncodedUnicodeCodePoint();if(0==d)return a;a+=String.fromCodePoint(d)}while(1)},function(){var a=this.readInt32();if(0==a)throw new e("String length can not be zero (as there's a trailing NULL)",{});for(var a=this._guardUnderflow(this.offset,a-1),d,c="";this.offset<a;)d=this.readUtf8EncodedUnicodeCodePoint(),c+=String.fromCodePoint(d);if(this.offset!=a)throw new e("Over-read '${size}' bytes of UTF-8 string of length '${length}'",
{size:this.offset-a,length:length-1});this.readTrailingNullByte();return c},function(){var a=this.readUint8();if(0!=a)throw new e("String trailing NUll was '${trailingNullByte}' not zero",{trailingNullByte:a});},function(){var b=this.readUint8(),d,c,e;if(128>b)return b;if(194>b)throw new a.InvalidUtf8CodePointException("Contination or overlong two byte sequence in first byte '${firstByte}' at offset ${offset}",{firstByte:b,offset:offset});if(224>b){d=this.readUint8();if(128!=(d&192))throw new a.InvalidUtf8CodePointException("Invalid two byte sequence in first byte '${firstByte}', second byte '${secondByte}' at offset ${offset}",
{firstByte:b,secondByte:d,offset:offset});return(b<<6)+d-12416}if(240>b){d=this.readUint8();if(128!=(d&192))throw new a.InvalidUtf8CodePointException("Invalid three byte sequence in first byte '${firstByte}', second byte '${secondByte}' at offset ${offset}",{firstByte:b,secondByte:d,offset:offset});if(224==b&&160>d)throw new a.InvalidUtf8CodePointException("Overlong two byte sequence in first byte '${firstByte}', second byte '${secondByte}' at offset ${offset}",{firstByte:b,secondByte:d,offset:offset});
c=this.readUint8();if(128!=(c&192))throw new a.InvalidUtf8CodePointException("Invalid two byte sequence in first byte '${firstByte}', second byte '${secondByte}', thirdByte '${thirdByte}' at offset ${offset}",{firstByte:b,secondByte:d,thirdByte:c,offset:offset});return(b<<12)+(d<<6)+c-925824}if(245>b){d=this.readUint8();if(128!=(d&192))throw new a.InvalidUtf8CodePointException("Invalid four byte sequence in first byte '${firstByte}', second byte '${secondByte}' at offset ${offset}",{firstByte:b,secondByte:d,
offset:offset});if(240==b&&144>d)throw new a.InvalidUtf8CodePointException("Overlong four byte sequence in first byte '${firstByte}', second byte '${secondByte}' at offset ${offset}",{firstByte:b,secondByte:d,offset:offset});if(244==b&&144<=d)throw new a.InvalidUtf8CodePointException("UCS-2 (> U+10FFFF) four byte sequence in first byte '${firstByte}', second byte '${secondByte}' at offset ${offset}",{firstByte:b,secondByte:d,offset:offset});c=this.readUint8();if(128!=(c&192))throw new a.InvalidUtf8CodePointException("Invalid four byte sequence in first byte '${firstByte}', second byte '${secondByte}', third byte '${thirdByte}' at offset ${offset}",
{firstByte:b,secondByte:d,thirdByte:c,offset:offset});e=this.readUint8();if(128!=(e&192))throw new a.InvalidUtf8CodePointException("Invalid four byte sequence in first byte '${firstByte}', second byte '${secondByte}', third byte '${thirdByte}', fourthByte '${fourthByte}' at offset ${offset}",{firstByte:b,secondByte:d,thirdByte:c,fourthByte:e,offset:offset});return(b<<18)+(d<<12)+(c<<6)+e-63447168}throw new a.InvalidUtf8CodePointException("UCS-2 (> U+10FFFF) byte sequences are not supported (first byte '${firstByte}') at offset ${offset}",
{firstByte:b,offset:offset});});return a}(MongoModule.BsonReader||{});MongoModule.ResultHandlers=function(a){return a}(MongoModule.ResultHandlers||{});"use strict";MongoModule.ResultHandlers=function(a){var e=ClassModule.safeHasOwnProperty;a.getValueOrDefault=function(a,d,c){return e(a,d)?a[d].value:c};return a}(MongoModule.ResultHandlers||{});"use strict";
MongoModule.ResultHandlers=function(a){var e=ClassModule.VirtualMethodException;ClassModule.Object.extend(a,function d(){this.super(d)},function(a,c,g,m){throw new e;});a.ResultHandler.NoMoreResults={getMore:!1,batchSize:0};a.ResultHandler.AnyNumberMoreResults={getMore:!0,batchSize:0};return a}(MongoModule.ResultHandlers||{});"use strict";
MongoModule.ResultHandlers=function(a){a.ResultHandler.extend(a,function b(a){this.super(b);this.callback=a},function(){var a=this.callback;a instanceof Function&&a.apply(this,Array.prototype.slice.call(arguments))});return a}(MongoModule.ResultHandlers||{});"use strict";
MongoModule.ResultHandlers=function(a){var e=a.ResultHandler.NoMoreResults;a.AbstractResultHandler.extend(a,function d(a,e,m,n){this.super(d);this.callback=a;this.actualBatchSize=e;this.requestedBatchSize=m;this.limit=n;this.batchIndicator=this.documentIndex=0;this.getMoreBatchSizeTuple={getMore:!0,actualBatchSize:e}},function(d,c,g,m){var n=this.callback;if(g)return n(!0,"Cursor not found"),e;if(m){if(1!=d.length)throw new TemplatedException("Did not expect more than one document for Command (got '${length}')",
{length:d.length});d=a.getValueOrDefault(d[0].value,"$err","No supplied error message");n(!0,d);return e}var h=this.actualBatchSize,f=this.limit,k=this.documentIndex,l=this.batchIndicator,q=d.length,p;d.forEach(function(a,d){if(k==f)return e;p=n(!1,a,!c||k==f-1,l,q,k,d,c,h,f);if(!1===p)return e;k+=1});if(k==f)return e;if(c){this.documentIndex=k;this.batchIndicator=l+1;d=f-k;if(d>h)return this.getMoreBatchSizeTuple;g={getMore:!0};g.actualBatchSize=-d;return g}return e});return a}(MongoModule.ResultHandlers||
{});"use strict";
MongoModule.ResultHandlers=function(a){var e=ClassModule.TemplatedException,b=a.ResultHandler.NoMoreResults,d=ClassModule.VirtualMethodException,c=MongoModule.BsonValues.BooleanBsonValue,g=MongoModule.BsonValues.Int32BsonValue,m=MongoModule.BsonValues.Int64BsonValue,n=MongoModule.BsonValues.DoubleBsonValue;a.AbstractResultHandler.extend(a,function f(a){this.super(f,a)},function(d,k,l,q){if(k)throw new e("Did not expect moreAvailable for Command",{});if(l)throw new e("Did not expect wasCursorNotFound for Command",{});
if(q)throw new e("Did not expect didGetMoreOrQueryButNotCommandFail for Command",{});if(1!=d.length)throw new e("Did not expect more than one document for Command (got '${length}')",{length:d.length});d=d[0].value;(k=d.ok)&&(k instanceof c?k.isTrue():(k instanceof g||k instanceof m||k instanceof n)&&k.isOne())?this.useUnwrappedCommandResultDocument(d):(k=a.getValueOrDefault(d,"code",-1),d=a.getValueOrDefault(d,"errmsg",""),this.commandError(k,d));return b},function(a,b){throw new d;},function(a){throw new d;
});return a}(MongoModule.ResultHandlers||{});"use strict";MongoModule.ResultHandlers=function(a){var e=ClassModule.TemplatedException;a.AbstractCommandResultHandler.extend(a,function d(a){this.super(d,a)},function(a,c){throw new e("IsMaster command failed with code '${errorCode}' and message '${errorMessage}",{errorCode:a,errorMessage:c});});return a}(MongoModule.ResultHandlers||{});"use strict";
MongoModule.ResultHandlers=function(a){a.AbstractUnfailingCommandResultHandler.extend(a,function b(a){this.super(b);this.callback=a},function(a){this.doCallback(a)});return a}(MongoModule.ResultHandlers||{});"use strict";
MongoModule.ResultHandlers=function(a){function e(a){return a&&a instanceof b?0!=a.length:!1}var b=MongoModule.BsonValues.ArrayBsonValue;a.AbstractUnfailingCommandResultHandler.extend(a,function c(a){this.super(c);this.callback=a},function(a){this.doCallback(e(a.users))});return a}(MongoModule.ResultHandlers||{});"use strict";
MongoModule.ResultHandlers=function(a){var e=MongoModule.ServerTypes.REPLICA_SET_PRIMARY,b=MongoModule.ServerTypes.REPLICA_SET_SECONDARY,d=MongoModule.ServerTypes.REPLICA_SET_ARBITER,c=MongoModule.ServerTypes.REPLICA_SET_OTHER,g=MongoModule.ServerTypes.REPLICA_SET_GHOST,m=MongoModule.ServerTypes.SHARD_ROUTER,n=MongoModule.ServerTypes.STANDALONE,h=ClassModule.safeHasOwnProperty;a.AbstractUnfailingCommandResultHandler.extend(a,function k(a){this.super(k,a)},function(k){var l;l=h(k,"setName")?!0:a.getValueOrDefault("isreplicaset",
!1);l=l?a.getValueOrDefault(k,"ismaster",!1)?e:a.getValueOrDefault(k,"secondary",!1)?b:a.getValueOrDefault(k,"arbiterOnly",!1)?d:h(k,"setName")&&h(k,"hosts")?c:g:"isdbgrid"===a.getValueOrDefault(k,"msg","")?m:n;var q=a.getValueOrDefault(k,"maxWriteBatchSize",MongoModule.maximumBatchSize),p=a.getValueOrDefault(k,"maxBsonObjectSize",MongoModule.maximumDocumentSize);k=a.getValueOrDefault(k,"maxMessageSizeBytes",MongoModule.maximumMessageSize);this.doCallback(l,q,p,k)});return a}(MongoModule.ResultHandlers||
{});"use strict";MongoModule.ResultHandlers=function(a){a.AbstractUnfailingCommandResultHandler.extend(a,function b(a){this.super(b,a)},function(a){a=a.versionArray.value;this.doCallback(a[0].value,a[1].value,a[2].value)});return a}(MongoModule.ResultHandlers||{});"use strict";
MongoModule.ResultHandlers=function(a){var e=a.getValueOrDefault;a.AbstractUnfailingCommandResultHandler.extend(a,function d(a){this.super(d,a)},function(a){var c=a.connectionId.value,g=e(a,"n",0),m=e(a,"syncMillis",0),n=e(a,"writtenTo",null);a=e(a,"err",null);this.doCallback(c,g,m,n,a)});return a}(MongoModule.ResultHandlers||{});"use strict";
MongoModule.ResultHandlers=function(a){a.AbstractUnfailingCommandResultHandler.extend(a,function b(a){this.super(b,a)},function(a){this.doCallback(a.nonce.value)});return a}(MongoModule.ResultHandlers||{});"use strict";
MongoModule.ResultHandlers=function(a){a.AbstractCommandResultHandler.extend(a,function b(a,c,g){this.super(b,a);this.couldNotAuthenticateCallback=c;this.database=g},function(a,d){this.couldNotAuthenticateCallback(a,d)},function(a){this.doCallback(this.database)});return a}(MongoModule.ResultHandlers||{});MongoModule.Credentials=function(a){return a}(MongoModule.Credentials||{});"use strict";
MongoModule.Credentials=function(a){var e=MongoModule.BsonWriter.writeUtf16BigEndianStringAsUtf8At,b=MongoModule.BsonValues.lowerCaseHexStringMd5FromDataView;a.createAuthenticationHash=function(a,c){for(var g=new ArrayBuffer(4*a.length+7+c.length),m=new DataView(g),n=e(m,a,!1,0,m.byteLength),n=e(m,":mongo:",!1,n,m.byteLength),h=c.length,f,k=0;k<h;k++){f=c.charCodeAt(k);if(127<f)throw new ClassModule.IllegalArgumentException("Passwords must only contain ASCII characters",{});m.setUint8(n,f);n++}return b(new DataView(g,
0,n))};a.createKeyHash=function(a){var c=new ArrayBuffer(4*a.length),g=new DataView(c);a=e(g,a,!1,0,g.byteLength);return b(new DataView(c,0,a))};return a}(MongoModule.Credentials||{});"use strict";MongoModule.Credentials=function(a){var e=ClassModule.VirtualMethodException;ClassModule.Object.extend(a,function d(){this.super(d)},function(a,c,g){throw new e;},function(a){throw new e;});return a}(MongoModule.Credentials||{});"use strict";
MongoModule.Credentials=function(a){a.Credential.extend(a,function b(a){this.super(b);this.databaseName=a},function(a){return new MongoModule.Database(a,this.databaseName)});return a}(MongoModule.Credentials||{});"use strict";
MongoModule.Credentials=function(a){a.AbstractCredential.extend(a,function b(a,c,g){this.super(b,a);this.userName=c;this.authenticationHash=g},function(a,d,c){var g=this.loginDatabase(a),m=this.userName,n=this.authenticationHash;g.nonce(function(a){g.authFromHash(m,n,a,d,c)})},function(a){a.removeCredential(this.databaseName,this.userName)});return a}(MongoModule.Credentials||{});"use strict";
MongoModule.Credentials=function(a){a.HashedMongoChallengeResponseCredential.extend(a,function b(d,c,g){this.super(b,d,c,a.createAuthenticationHash(c,g))});return a}(MongoModule.Credentials||{});"use strict";
MongoModule.Credentials=function(a){ClassModule.Object.extend(a,function b(a){this.super(b);this.storage=(this.sharedComputerSoOnlyKeepForSession=a)?window.sessionStorage:window.localStorage},function(b,d){var c=this.__key(b,d);this.__removeCredentialFromLocalStorageIfUsingSessionStorage(c);return(c=this.storage.getItem(c))?new a.HashedMongoChallengeResponseCredential(b,d,c):null},function(b,d,c){var g=this.__key(b,d);this.__removeCredentialFromLocalStorageIfUsingSessionStorage(g);this.storage.setItem(g,
a.createAuthenticationHash(d,c));return this.getHashedMongoChallengeResponseCredential(b,c)},function(a,d){var c=this.__key(a,d);this.__removeCredentialFromLocalStorageIfUsingSessionStorage(c);this.storage.removeItem(c)},function(a){this.sharedComputerSoOnlyKeepForSession&&window.localStorage.removeItem(a)},function(a,d){return"mongo-user-hash."+a+"."+d});return a}(MongoModule.Credentials||{});"use strict";
MongoModule=function(a){function e(a,b,c){b=new WebSocket(b,[c]);b.binaryType="arraybuffer";b.onopen=function(a){return function(b){a.__opened()}}(a);b.onmessage=function(a){return function(b){a.__receive(b.data)}}(a);b.onerror=function(a){return function(a){console.warn("Error with WebSocket")}}(a);return b}function b(){var a=[];a.nextRequestIdCounter=1;a.nextRequestId=function(){var a=this.nextRequestIdCounter;this.nextRequestIdCounter+=1;return a};return a}var d=MongoModule.BsonWriter.BsonWriter,
c=MongoModule.BsonWriter.BsonWriterOverflowException,g=MongoModule.BsonReader.BsonReader,m=MongoModule.Messages.QueryMessage,n=MongoModule.Messages.InsertMessage,h=MongoModule.Messages.UpdateMessage,f=MongoModule.Messages.DeleteMessage,k=MongoModule.BsonValues.DocumentBsonValue,l=MongoModule.BsonValues.ObjectIdBsonValue,q=MongoModule.BsonValues.fromStrictJavascript,p=MongoModule.Messages.Message.readMessage;ClassModule.Object.extend(a,function v(c,d,f,g,h,k,l){this.super(v);this.writeConcern=ClassModule.default(h,
a.WriteConcerns.ACKNOWLEDGED);this.sendBufferInitialSize=ClassModule.default(k,131072);this.__webSocket=e(this,c,ClassModule.default(l,"binary"));this.__resultHandlerTuples=b();this.__partialMessageBuffer=new ArrayBuffer(0);this.__partialMessageBufferOffset=0;this.__beforeOpenSendQueue=[];this.maximumBatchSize=a.maximumBatchSize;this.maximumDocumentSize=a.maximumDocumentSize;this.maximumMessageSize=a.maximumMessageSize;var m=this;(function(){var b=new a.AdminDatabase(m);b.isMaster(function(a,c,e,
h){m.serverType=a;m.maximumBatchSize=c;m.maximumDocumentSize=e;m.maximumMessageSize=h;b.buildInfo(function(a,b,c){m.majorVersion=a;m.minorVersion=b;m.revisionVersion=c;m.serverType.isReplicaSetMemberArbiter?f(-1,"Server Type isReplicaSetMemberArbiter"):m.authenticate(d,f,function(a){a.getLastError(null,null,!1,!1,function(b,c,d,e,f){m.connectionId=b;g(a)})})})})})()},function(a,b,c){a.authenticate(this,b,c)},function(a,b){this.writeConcern.getLastError(a,b)},function(){var a=this;this.__beforeOpenSendQueue.forEach(function(b){a.__write(b.fullCollectionName,
b.resultHandler,b.message)});delete this.__beforeOpenSendQueue;this.send=this.__write},function(a,b,e){var f=this.sendBufferInitialSize,g,h,k;do{g=new ArrayBuffer(f);h=new d(g);try{k=e.writeBson(h)}catch(l){if(l instanceof c){f*=2;continue}console.warn(l.stack);throw l;}break}while(1);null!==b&&(this.__resultHandlerTuples[e.requestIdInt32]={fullCollectionName:a,resultHandler:b});a=g.slice(0,k);this.__webSocket.send(a);return this},function(a){var b=this.__partialMessageBuffer,c=this.__partialMessageBufferOffset,
d=b.byteLength-c,e=new Uint8Array(d+a.byteLength);e.set(new Uint8Array(b,c),0);e.set(new Uint8Array(a),d);this.__partialMessageBuffer=e.buffer;this.__partialMessageBufferOffset=0;for(a=new g(this.__partialMessageBuffer);a.hasCompleteMessageAvailable();)b=p(a),b.process(this,this.__resultHandlerTuples);this.__partialMessageBufferOffset=a.offset},function(b){return new a.Database(this,b)},function(){return new a.AdminDatabase(this)},function(a,b,c){return this.sendQuery(a,b,"$cmd",!1,0,-1,null,c)},
function(a,b,c,d,e,f,g,h){b=b+"."+c;c=this.__resultHandlerTuples.nextRequestId();return this.send(b,a,new m(c,0,d?4:0,b,e,f,q(h),null===g?null:q(g)))},function(a,b,c,d){a=a+"."+b;b=this.__resultHandlerTuples.nextRequestId();return this.send(a,null,new n(b,0,c?1:0,a,d.map(function(a){var b=l.generateNewObjectId();a instanceof k?a.value._id=b:a._id=b.toStrictJavaScriptValue();return q(a)})))},function(a,b,c,d,e,f){a=a+"."+b;b=this.__resultHandlerTuples.nextRequestId();var g=0;c&&(g|=1);d&&(g|=2);return this.send(a,
null,new h(b,0,0,a,g,q(e),q(f)))},function(a,b,c,d){a=a+"."+b;b=this.__resultHandlerTuples.nextRequestId();return this.send(a,null,new f(b,0,0,a,c?1:0,q(d)))},function(a,b,c){this.__beforeOpenSendQueue.push({fullCollectionName:a,resultHandler:b,message:c});return this});return a}(MongoModule||{});"use strict";
MongoModule=function(a){var e=MongoModule.BsonValues,b=e.StringBsonValue,d=e.DocumentBsonValue,c=e.Int32BsonValue,g=e.ArrayBsonValue,m=e.DoubleBsonValue,n=e.Int64BsonValue,h=c.One,e=e.BooleanBsonValue,f=e.bsonBoolean,k=e.BsonFalse,l=e.BsonTrue,q=MongoModule.BsonValues.fromStrictJavascript,e=MongoModule.ResultHandlers,p=e.NonceCommandResultHandler,t=e.AuthCommandResultHandler,v=e.GetLastErrorCommandResultHandler,r=e.VoidCommandResultHandler,x=e.UserExistsCommandResultHandler,w=e.QueryResultsHandler;
ClassModule.Object.extend(a,function u(a,b){this.super(u);this.connection=a;this.databaseName=b},function(b){return new a.Collection(this,b)},function(a){return this.sendCommand(new p(a),{getnonce:h})},function(a,c,d,e,f){c=MongoModule.Credentials.createKeyHash(d+a+c);return this.sendCommand(new t(f,e,this),{authenticate:h,user:new b(a),nonce:new b(d),key:new b(c)})},function(a,d,e,f,g){var k={getLastError:h};a&&null!==a&&(k.w="majority"===a?new b("majority"):new c(a),d&&0<d&&(k.wtimeout=d));e&&(k.fsync=
l);f&&(k.j=l);return this.sendCommand(new v(g),k)},function(a,b,c,d,e,f,g,h){var k={};k.$query=q(b);h&&0<h&&(k.$maxTimeMS=n.fromUnsigned32BitInteger(h));this.connection.sendQuery(new w(d,e,f),this.databaseName,a,!0,g,e,c,k);return this},function(a,b,c,d){var e=this.connection;e.sendInsert(this.databaseName,a,b,d);e.getLastError(this,c);return this},function(a,b,c,d,e,f){var g=this.connection,h=this.databaseName,k=this;f.forEach(function(f){g.sendUpdate(h,a,b,c,d,f);g.getLastError(k,e)});return this},
function(a,b,c,d){var e=this.connection;e.sendDelete(this.databaseName,a,b,d);e.getLastError(this,c);return this},function(a,b){this.connection.sendCommand(a,this.databaseName,b);return this},function(a,b,c,d){return this.findDocuments("system.namespaces",{},null,a,b,c,d)},function(a,b,c,e,f){return this.sendCommand(new w(c,e,f),this.databaseName,{listCollections:h,cursor:new d({batchSize:e}),filter:new d(b),maxTimeMS:n.fromUnsigned32BitInteger(a)})},function(a,b){return this.sendCommand(new x(b),
{usersInfo:new BsonStringValue(a)})},function(a,c,d,e,g,h,k){return this.sendCommand(new r(k),{create:new b(a),capped:f(c),size:n.fromUnsigned32BitInteger(d),autoIndexId:f(e),max:n.fromUnsigned32BitInteger(g),usePowerOfTwoSizes:f(h)})},function(a,c){var e=[];Array.prototype.slice.call(arguments,3).forEach(function(a){e.push(new d(a))});return this.sendCommand(new r(c),{createIndexes:new b(a),indexes:new g(e)})},function(a,c,d){var e=[];Array.prototype.slice.call(arguments,4).forEach(function(a){e.push(new b(a))});
return this.sendCommand(new r(d),{createUser:new b(a),pwd:new b(MongoModule.Credentials.UserNamePasswordMongoChallengeResponseCredential.createAuthenticationHash(a,c)),digestPassword:k,roles:new g(e)})},function(a,c){return this.sendCommand(new r(c),{drop:new b(a)})},function(a){return this.sendCommand(new r(a),{dropDatabase:h})},function(a,c,d){return this.sendCommand(new r(d),{dropIndexes:new b(a),index:new b(c)})},function(a,c){return this.sendCommand(new r(c),{dropUser:new b(a)})});a.indexCreationDocument=
function(a,e,g,h,k,l,n,p,q,r,t,v,x,w,A,y,z,B){a={key:new d(a),name:new b(e),ns:new b(g),background:f(h),unique:f(h),sparse:f(l),dropDups:f(B)};null!=n&&(a.expireAfterSeconds=new c(n));null!=p&&(a.v=new c(p));null!=q&&(a.weights=new d(q));null!=default_language&&(a.default_language=new b(r));null!=language_override&&(a.language_override=new b(t));null!=v&&(a.textIndexVersion=new c(v));null!=x&&(a["2dsphereIndexVersion"]=new c(x));null!=w&&(a.bits=new c(w));null!=A&&(a.min=new m(w));null!=y&&(a.max=
new m(y));null!=z&&(a.bucketSize=new m(z));return a};return a}(MongoModule||{});"use strict";MongoModule=function(a){var e=MongoModule.BsonValues.Int32BsonValue.One,b=MongoModule.ResultHandlers.IsMasterCommandResultHandler,d=MongoModule.ResultHandlers.BuildInfoCommandResultHandler;a.Database.extend(a,function g(a){this.super(g,a,"admin")},function(a){return this.sendCommand(new b(a),{ismaster:e})},function(a){return this.sendCommand(new d(a),{buildinfo:e})});return a}(MongoModule||{});"use strict";
MongoModule=function(a){ClassModule.Object.extend(a,function b(a,c){this.super(b);this.database=a;this.collectionName=c},function(a,d,c,g,m,n,h){this.database.find(this.collectionName,a,d,c,g,m,n,h);return this},function(a,d,c){var g;g=3==arguments.length?c instanceof Array?c:[c]:Array.prototype.slice.call(arguments,2);this.database.insert(this.collectionName,a,d,g);return this},function(a,d,c,g,m){var n;n=5==arguments.length?m instanceof Array?m:[m]:Array.prototype.slice.call(arguments,4);this.database.update(this.collectionName,
a,d,c,g,n);return this},function(a,d,c){this.database.deleteMatching(this.collectionName,a,d,c);return this});return a}(MongoModule||{});"use strict";
MongoModule=function(a){ClassModule.Object.extend(a,function(a,d,c,e){this.waitForReplicationToNServersWhereOneIsSelfOrWaitForMajorityBeforeReturning=a;this.timeoutWaitForReplicationMilliseconds=d;this.waitForFsyncBeforeReturning=c;this.waitForJournalBeforeReturning=e;this.isAcknowledged=0<a},function(a,d){if(this.isAcknowledged)return a.getLastError(this.waitForReplicationToNServersWhereOneIsSelfOrWaitForMajorityBeforeReturning,this.timeoutWaitForReplicationMilliseconds,this.waitForFsyncBeforeReturning,
this.waitForJournalBeforeReturning);d(a.connection.connectionId,null,null,null,null)});var e=a.WriteConcern;a.WriteConcerns={ACKNOWLEDGED:new e(1,0,!1,!1),UNACKNOWLEDGED:new e(0,0,!1,!1),FSYNCED:new e(1,0,!0,!1),JOURNALED:new e(1,0,!1,!0),REPLICA_ACKNOWLEDGED:new e(2,0,!1,!1),MAJORITY:new e("majority",0,!1,!1)};return a}(MongoModule||{});
